# Generated by Django 5.1.7 on 2025-06-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_profile_estatus_alter_bitacora_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
