# Generated by Django 5.1.7 on 2025-06-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_task'),
        ('dashboard', '0006_bitacora_user_profile_user_alter_profile_phone_and_more'),
    ]

    operations = [
    ]
